---
name: Overseerr
version: 0.2.4
slug: overseerr
description: Overseerr is a request management and media discovery tool
url: "https://github.com/hoopty/hassio-addons/tree/main/overseerr#readme"
arch:
  - aarch64
  - amd64
  - armhf
init: false
map:
  - config:rw
backup_exclude:
  - "**/logs/*"
options:
  PUID: 1001
  PGID: 1001
ports:
  5055/tcp: 5055
ports_description:
  5055/tcp: web interface
schema:
  PUID: int
  PGID: int
  TZ: "str?"
webui: http://[HOST]:[PORT:5055]
image: "ghcr.io/hoopty/hassio-overseerr-{arch}"
