---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.get-dirs.outputs.dir }} # generate output name dir by using inner step output
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Get Directories
        id: get-dirs # Give it an id to handle to get step outputs in the outputs key above
        # yamllint disable-line rule:line-length
        run: echo "::set-output name=dir::$(ls -d */ | sed 's|/$||g' | jq -R -s -c 'split("\n")[:-1]')"

  loop:
    name: Build
    runs-on: ubuntu-latest
    needs: [prepare] # Depends on previous job
    strategy:
      matrix:
        dir: ${{fromJson(needs.prepare.outputs.dir)}}
    steps:
      - name: Test Build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --armhf --amd64 --aarch64 \
            --target ${{matrix.dir}} \
            --docker-hub ${{ secrets.DOCKERHUB_USERNAME }}
