---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
      # addons: ${{ steps.addons.outputs.addons }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Information
        id: info
        uses: home-assistant/actions/helpers/info@master

      # - name: Get Addons
      #   id: addons
      #   # yamllint disable-line rule:line-length
      #   run: echo "::set-output name=addons::$(ls -d */ | sed 's|/$||g' | jq -R -s -c 'split("\n")[:-1]')"

  build:
    name: Build
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        architecture: ${{ fromJson(needs.init.outputs.architectures) }}
        # addons: ${{fromJson(needs.init.outputs.addons)}}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.4.0

      - name: Build the builder
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --amd64 \
            --target /data/overseerr \
            --generic latest

      - name: Test ${{ matrix.architecture }} builder
        uses: ./
        with:
          args: |
            --test \
            --${{ matrix.architecture }} \
            --target /data/overseerr \
            --generic ${{ github.sha }}
            # --docker-hub ${{ secrets.DOCKERHUB_USERNAME }}
