---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      # architectures: ${{ steps.info.outputs.architectures }}
      addons: ${{ steps.addons.outputs.addons }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Get Information
      #   id: info
      #   uses: home-assistant/actions/helpers/info@master

      - name: Get Addons
        id: addons
        # yamllint disable-line rule:line-length
        run: echo "::set-output name=addons::$(ls -d */ | sed 's|/$||g' | jq -R -s -c 'split("\n")[:-1]')"

  build:
    name: Build
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        addon: [overseerr]
        architecture: [amd64]
        # architecture: [aarch64,amd64,armhf]
        # architecture: ${{ fromJson(needs.init.outputs.architectures) }}
        # addons: ${{fromJson(needs.init.outputs.addons)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: ./${{ matrix.addon }}

      - name: Test ${{ matrix.addon }}-${{ matrix.architecture }}
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --${{ matrix.architecture }} \
            --target /data/${{ matrix.addon }} \
            --docker-hub ${{ secrets.DOCKERHUB_USERNAME }}
