name: CI

on: [push, pull_request]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.get-dirs.outputs.dir }} # generate output name dir by using inner step output
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Get Directories
        id: get-dirs # Give it an id to handle to get step outputs in the outputs key above
        run: echo "::set-output name=dir::$( find . -type d -depth 1 ! -name '.*' | sed 's|^./||g' | jq -R -s -c 'split("\n")[:-1]' )"

  loop:
    name: Build
    runs-on: ubuntu-latest
    needs: [prepare] # Depends on previous job
    strategy:
      matrix:
        dir: ${{fromJson(needs.prepare.outputs.dir)}}
    steps:
      - name: Test Build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --all \
            --target ${{matrix.dir}} \
            --docker-hub ${{ secrets.DOCKERHUB_USERNAME }}

