---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  init:
    name: Initialize
    runs-on: ubuntu-latest
    outputs:
      addons: ${{ steps.addons.outputs.addons }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Addons
        id: addons
        # yamllint disable-line rule:line-length
        run: echo "::set-output name=addons::$(ls -d */ | sed 's|/$||g' | jq -R -s -c 'split("\n")[:-1]')"

  build:
    name: Build
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        addon: [overseerr]
        arch: [aarch64,amd64,armhf]
        # arch: ${{ fromJson(needs.init.outputs.archs) }}
        # addons: ${{fromJson(needs.init.outputs.addons)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: ./${{ matrix.addon }}

      - name: Test ${{ matrix.addon }}-${{ matrix.arch }}
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --${{ matrix.arch }} \
            --target /data/${{ matrix.addon }}
