name: Publish

on:
  release:
    types: [published]

jobs:
  prepare: 
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }} # generate output name dir by using inner step output
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get Directories
        id: set-dirs # Give it an id to handle to get step outputs in the outputs key above
        run: echo "::set-output name=dir::$(ls -d */ | jq -R -s -c 'split("\n")[:-1]')"

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [prepare] # Depends on previous job 
    strategy:
      matrix:
        dir: ${{fromJson(needs.prepare.outputs.dir)}} 
    steps:
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target ${{matrix.dir}} \
            --docker-hub ${{ secrets.DOCKERHUB_USERNAME }}

