---
name: Publish

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        addon: [overseerr]
        arch: [aarch64,amd64,armhf]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: ./${{ matrix.addon }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish ${{ matrix.addon }}-${{ matrix.arch }}
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }} \
            --image hassio-${{ matrix.addon }}-${{ matrix.arch }} \
            --target /data/${{ matrix.addon }} \
            --docker-hub "ghcr.io/${{ github.repository_owner }}"
